export type AppLanguage = "es" | "ca";

export const LANGUAGE_COOKIE = "app_language";

export const LANGUAGES: Array<{ value: AppLanguage; label: string }> = [
  { value: "es", label: "Castellano" },
  { value: "ca", label: "Català" },
];

const monthNames: Record<string, string> = {
  Enero: "Gener",
  Febrero: "Febrer",
  Marzo: "Març",
  Abril: "Abril",
  Mayo: "Maig",
  Junio: "Juny",
  Julio: "Juliol",
  Agosto: "Agost",
  Septiembre: "Setembre",
  Octubre: "Octubre",
  Noviembre: "Novembre",
  Diciembre: "Desembre",
  ene: "gen",
  feb: "febr",
  mar: "març",
  abr: "abr",
  may: "maig",
  jun: "juny",
  jul: "jul",
  ago: "ag",
  sept: "set",
  oct: "oct",
  nov: "nov",
  dic: "des",
};

const caDictionary: Record<string, string> = {
  "Resumen": "Resum",
  "Resumen mensual": "Resum mensual",
  "Visión global": "Visió global",
  "Presupuestos": "Pressupostos",
  "Presupuestos mensuales": "Pressupostos mensuals",
  "Compartidos": "Compartits",
  "Importar": "Importar",
  "Informes": "Informes",
  "Informes y exportación": "Informes i exportació",
  "Ajustes": "Configuració",
  "Perfil": "Perfil",
  "Usuario": "Usuari",
  "Modo claro": "Mode clar",
  "Modo oscuro": "Mode fosc",
  "Editar perfil": "Editar perfil",
  "Cerrar sesión": "Tancar sessió",
  "¿Cerrar sesión?": "Tancar sessió?",
  "Cancelar": "Cancel·lar",
  "Atrás": "Enrere",
  "Siguiente": "Següent",
  "Terminar": "Finalitzar",
  "Sí": "Sí",
  "No": "No",
  "Idioma": "Idioma",
  "Castellano": "Castellà",
  "Català": "Català",
  "Preferencias": "Preferències",
  "Datos personales": "Dades personals",
  "Nombre": "Nom",
  "Guardar": "Desar",
  "Correo asociado": "Correu associat",
  "Contraseña": "Contrasenya",
  "Cambiar contraseña": "Canviar contrasenya",
  "Contraseña actual": "Contrasenya actual",
  "Nueva contraseña": "Nova contrasenya",
  "Confirmar nueva": "Confirmar nova",
  "Guardar nueva contraseña": "Desar nova contrasenya",
  "Contraseña cambiada.": "Contrasenya canviada.",
  "Grupos asociados": "Grups associats",
  "Sesión": "Sessió",
  "Eliminar cuenta": "Eliminar compte",
  "Eliminar mi cuenta": "Eliminar el meu compte",
  "Eliminar cuenta permanentemente": "Eliminar el compte permanentment",
  "Escribe tu correo para confirmar": "Escriu el teu correu per confirmar",
  "Activo": "Actiu",
  "Pendiente": "Pendent",
  "Propietario": "Propietari",
  "Miembro": "Membre",
  "Ingreso mensual": "Ingrés mensual",
  "Ingreso mensual / salario": "Ingrés mensual / salari",
  "Gastos mensuales fijos": "Despeses mensuals fixes",
  "Añadir gasto fijo": "Afegir despesa fixa",
  "Editar gasto fijo": "Editar despesa fixa",
  "Presupuestos por categoría": "Pressupostos per categoria",
  "Categorías personalizadas": "Categories personalitzades",
  "Nombre de la categoría": "Nom de la categoria",
  "Gasto": "Despesa",
  "Ingreso": "Ingrés",
  "Añadir": "Afegir",
  "Categoría": "Categoria",
  "Sin categoría": "Sense categoria",
  "Todas": "Totes",
  "Todos": "Tots",
  "Importe": "Import",
  "Importe (€)": "Import (€)",
  "Fecha real": "Data real",
  "Notas": "Notes",
  "Notas (opcional)": "Notes (opcional)",
  "Adjunto (opcional)": "Adjunt (opcional)",
  "Método de pago": "Mètode de pagament",
  "Selecciona una categoría": "Selecciona una categoria",
  "Selecciona un método": "Selecciona un mètode",
  "Compra supermercado": "Compra supermercat",
  "Nómina": "Nòmina",
  "Tarjeta": "Targeta",
  "Efectivo": "Efectiu",
  "Transferencia": "Transferència",
  "Domiciliación": "Domiciliació",
  "Bizum": "Bizum",
  "Otro": "Altre",
  "Otros": "Altres",
  "Guardar gasto": "Desar despesa",
  "Guardar ingreso": "Desar ingrés",
  "Guardando…": "Desant…",
  "Editar gasto": "Editar despesa",
  "Editar ingreso": "Editar ingrés",
  "Nuevo gasto": "Nova despesa",
  "Nuevo ingreso": "Nou ingrés",
  "Movimiento actualizado.": "Moviment actualitzat.",
  "Movimiento guardado.": "Moviment desat.",
  "Eliminado.": "Eliminat.",
  "Editar": "Editar",
  "Eliminar": "Eliminar",
  "Restaurar": "Restaurar",
  "Descartar": "Descartar",
  "Gastos": "Despeses",
  "Ingresos": "Ingressos",
  "Ahorro": "Estalvi",
  "Ahorro total": "Estalvi total",
  "Gastos por categoría": "Despeses per categoria",
  "Ingresos vs gastos": "Ingressos vs despeses",
  "Gastos compartidos": "Despeses compartides",
  "Presupuestos del mes": "Pressupostos del mes",
  "Gastos previstos": "Despeses previstes",
  "Gasto previsto añadido.": "Despesa prevista afegida.",
  "Presupuesto cerrado.": "Pressupost tancat.",
  "Ver opciones": "Veure opcions",
  "Ocultar": "Amagar",
  "Ver 2026 completo": "Veure 2026 complet",
  "Ocultar año": "Amagar any",
  "Vista global 2026": "Vista global 2026",
  "Vista global": "Visió global",
  "Presupuesto previsto por mes y comparación con el gasto real.": "Pressupost previst per mes i comparació amb la despesa real.",
  "Evolución del gasto": "Evolució de la despesa",
  "Gastos previstos vs gastos reales": "Despeses previstes vs despeses reals",
  "Dónde más gastas": "On gastes més",
  "Meses previstos": "Mesos previstos",
  "Previsto": "Previst",
  "Real": "Real",
  "Diferencia": "Diferència",
  "Cerrar mes": "Tancar mes",
  "Gastaste menos": "Has gastat menys",
  "Cumplido": "Complert",
  "Te pasaste": "T'has passat",
  "Guardar cierre": "Desar tancament",
  "Mapa mensual": "Mapa mensual",
  "Partida": "Partida",
  "Partidas": "Partides",
  "Nota del cierre": "Nota del tancament",
  "Abierto": "Obert",
  "Generar informes": "Generar informes",
  "Generar informe": "Generar informe",
  "Regenerar informe": "Regenerar informe",
  "Solo se puede generar un informe con IA por mes.": "Només es pot generar un informe amb IA per mes.",
  "Puedes generar 1 informe IA este mes.": "Pots generar 1 informe IA aquest mes.",
  "Ya has utilizado el informe IA de este mes.": "Ja has utilitzat l'informe IA d'aquest mes.",
  "Para controlar el coste de IA, la app permite solo un informe por mes natural.": "Per controlar el cost d'IA, l'app permet només un informe per mes natural.",
  "Para controlar el coste de IA, la app permite solo un informe por mes natural y no permite repetir informes ya creados.": "Per controlar el cost d'IA, l'app permet només un informe per mes natural i no permet repetir informes ja creats.",
  "Próxima generación disponible el mes siguiente.": "Propera generació disponible el mes següent.",
  "Mes de cuota:": "Mes de quota:",
  "Disponible": "Disponible",
  "Usado": "Utilitzat",
  "Informe mensual usado": "Informe mensual utilitzat",
  "Informe ya creado": "Informe ja creat",
  "Ya existe un informe para este periodo.": "Ja existeix un informe per a aquest període.",
  "Ya existe un informe para el periodo seleccionado.": "Ja existeix un informe per al període seleccionat.",
  "Ya existe un informe para el periodo seleccionado. Puedes verlo en el historial, pero no volver a generarlo.": "Ja existeix un informe per al període seleccionat. Pots veure'l a l'historial, però no tornar-lo a generar.",
  "Ya has generado el informe IA permitido este mes.": "Ja has generat l'informe IA permès aquest mes.",
  "Informes IA": "Informes IA",
  "Exportación de datos": "Exportació de dades",
  "Descarga tus movimientos y resúmenes.": "Descarrega els teus moviments i resums.",
  "Exportar CSV": "Exportar CSV",
  "Exportar Excel": "Exportar Excel",
  "Resumen mensual (Excel)": "Resum mensual (Excel)",
  "Ámbito": "Àmbit",
  "Finanzas personales": "Finances personals",
  "Tipo de dato": "Tipus de dada",
  "Gastos e ingresos": "Despeses i ingressos",
  "Solo gastos": "Només despeses",
  "Solo ingresos": "Només ingressos",
  "Periodo (mes o año, vacío = todo)": "Període (mes o any, buit = tot)",
  "Crear cuenta": "Crear compte",
  "Iniciar sesión": "Iniciar sessió",
  "Accede a tus finanzas personales y compartidas": "Accedeix a les teves finances personals i compartides",
  "Empieza a controlar tus finanzas en minutos": "Comença a controlar les teves finances en minuts",
  "Recuperar contraseña": "Recuperar contrasenya",
  "Enviar enlace": "Enviar enllaç",
  "Email": "Email",
  "Mínimo 8 caracteres.": "Mínim 8 caràcters.",
  "Confirmar contraseña": "Confirmar contrasenya",
  "Guardar contraseña": "Desar contrasenya",
  "Instalar la aplicación": "Instal·lar l'aplicació",
  "Notificaciones": "Notificacions",
  "¿Activamos las notificaciones?": "Activem les notificacions?",
  "Bienvenida": "Benvinguda",
  "Ahorrar más": "Estalviar més",
  "Reducir gastos": "Reduir despeses",
  "Controlar gastos": "Controlar despeses",
  "Pagar deudas": "Pagar deutes",
  "Invertir": "Invertir",
  "Gestionar gastos compartidos": "Gestionar despeses compartides",
  "Restaurantes": "Restaurants",
  "Compras online": "Compres online",
  "Supermercado": "Supermercat",
  "Transporte": "Transport",
  "Ocio": "Oci",
  "Viajes": "Viatges",
  "Suscripciones": "Subscripcions",
  "Alquiler": "Lloguer",
  "Hipoteca": "Hipoteca",
  "Servicios": "Serveis",
  "Seguros": "Assegurances",
  "Luz": "Llum",
  "Agua": "Aigua",
  "Gas": "Gas",
  "Seguro coche": "Assegurança cotxe",
  "Seguro casa": "Assegurança casa",
  "Impuestos": "Impostos",
  "¿Cuál es tu objetivo financiero principal?": "Quin és el teu objectiu financer principal?",
  "Cuéntanos tu objetivo": "Explica'ns el teu objectiu",
  "¿Cuáles son tus hábitos de consumo principales?": "Quins són els teus hàbits de consum principals?",
  "Selecciona todos los que apliquen.": "Selecciona tots els que corresponguin.",
  "¿Cuál es tu ingreso mensual (salario)?": "Quin és el teu ingrés mensual (salari)?",
  "Importe aproximado (€/mes)": "Import aproximat (€/mes)",
  "¿Tienes gastos fijos mensuales?": "Tens despeses fixes mensuals?",
  "Selecciona los que tengas.": "Selecciona les que tinguis.",
  "¿Inviertes actualmente?": "Inverteixes actualment?",
  "¿En qué inviertes?": "En què inverteixes?",
  "Fondos indexados, acciones, cripto…": "Fons indexats, accions, cripto…",
  "Mensual (€)": "Mensual (€)",
  "Puntual (€)": "Puntual (€)",
  "Capital acumulado aproximado (€)": "Capital acumulat aproximat (€)",
  "¿Quieres subir un extracto bancario?": "Vols pujar un extracte bancari?",
  "Pulsa para seleccionar un archivo": "Prem per seleccionar un arxiu",
  "¿Quieres crear un grupo de gastos compartidos?": "Vols crear un grup de despeses compartides?",
  "Sirve para invitar a otras personas, repartir gastos y ver métricas del grupo dentro de la app.": "Serveix per convidar altres persones, repartir despeses i veure mètriques del grup dins de l'app.",
  "Nombre del grupo": "Nom del grup",
  "Invita por email (uno por línea)": "Convida per email (un per línia)",
  "¿Qué gastos soléis compartir?": "Quines despeses soleu compartir?",
  "Importar documentos": "Importar documents",
  "Revisar importación": "Revisar importació",
  "Tipo": "Tipus",
  "Concepto": "Concepte",
  "Detalle mensual": "Detall mensual",
  "Mes": "Mes",
  "Estado": "Estat",
  "Pagado": "Pagat",
  "Le corresponde": "Li correspon",
  "Balance": "Balanç",
  "Deudas pendientes": "Deutes pendents",
  "Integrante": "Integrant",
  "Invitar al grupo": "Convidar al grup",
  "Nuevo grupo de gastos compartidos": "Nou grup de despeses compartides",
  "Pagado por": "Pagat per",
  "Se comparte entre": "Es comparteix entre",
  "Ticket o factura": "Tiquet o factura",
  "Enlace del justificante": "Enllaç del justificant",
  "Registrar pago parcial": "Registrar pagament parcial",
};

export function normalizeLanguage(value: string | undefined | null): AppLanguage {
  return value === "ca" ? "ca" : "es";
}

function translateMonths(value: string) {
  return value.replace(
    /\b(Enero|Febrero|Marzo|Abril|Mayo|Junio|Julio|Agosto|Septiembre|Octubre|Noviembre|Diciembre|ene|feb|mar|abr|may|jun|jul|ago|sept|oct|nov|dic)\b/g,
    (match) => monthNames[match] ?? match
  );
}

function translatePatterns(value: string) {
  const next = value
    .replace("Último intento:", "Últim intent:")
    .replace("Mes de cuota:", "Mes de quota:");
  const patterns: Array<[RegExp, string]> = [
    [/^Vista global (\d{4})$/, "Visió global $1"],
    [/^Gastos \((\d+)\)$/, "Despeses ($1)"],
    [/^Ingresos \((\d+)\)$/, "Ingressos ($1)"],
    [/^Partidas de (.+)\.$/, "Partides de $1."],
    [/^(.+) de (\d{4})$/, "$1 de $2"],
  ];

  for (const [pattern, replacement] of patterns) {
    if (pattern.test(next)) return next.replace(pattern, replacement);
  }

  return next;
}

export function translateUiText(value: string, language: AppLanguage) {
  if (language === "es") return value;
  const exact = caDictionary[value];
  if (exact) return exact;
  return translateMonths(translatePatterns(value));
}
